server:
  port: 2001
spring:
  application:
    name: demo-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  instance:
      hostname: localhost
      instanceId: http://localhost:2001